using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public enum ChangeType
{
    MAT_MATTE_GREY, MAT_MATTE_RED, MAT_MATTE_BLUE, MAT_MATTE_YELLOW,
    MAT_METAL_GREY, MAT_METAL_RED, MAT_METAL_BLUE, MAT_METAL_YELLOW,
    MAT_CHECKERED_GREY, MAT_CHECKERED_RED, MAT_CHECKERED_BLUE, MAT_CHECKERED_YELLOW,
    MAT_ABSTRACT_GREY, MAT_ABSTRACT_RED, MAT_ABSTRACT_BLUE, MAT_ABSTRACT_YELLOW,
    SHAPE_OCTAHEDRON, SHAPE_CUBE, SHAPE_TETRAHEDRON, SHAPE_DODECAHEDRON,
    SIZE_XSMALL, SIZE_SMALL, SIZE_NORMAL, SIZE_BIG, SIZE_XBIG
}
